branches:
  except:
    - travis

language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew
 
cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1
    
script:
  - ./gradlew clean check --info
  - ./gradlew compileJava --info
  - ./gradlew jar --info

after_success:
 - ./gradlew jacocoTestReport
 - bash <(curl -s https://codecov.io/bash)
